/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VtcAeroportToulouseBlagnacRouteImport } from './routes/vtc-aeroport-toulouse-blagnac'
import { Route as PolitiqueConfidentialiteRouteImport } from './routes/politique-confidentialite'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as IndexRouteImport } from './routes/index'

const VtcAeroportToulouseBlagnacRoute =
  VtcAeroportToulouseBlagnacRouteImport.update({
    id: '/vtc-aeroport-toulouse-blagnac',
    path: '/vtc-aeroport-toulouse-blagnac',
    getParentRoute: () => rootRouteImport,
  } as any)
const PolitiqueConfidentialiteRoute =
  PolitiqueConfidentialiteRouteImport.update({
    id: '/politique-confidentialite',
    path: '/politique-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/vtc-aeroport-toulouse-blagnac': typeof VtcAeroportToulouseBlagnacRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/vtc-aeroport-toulouse-blagnac': typeof VtcAeroportToulouseBlagnacRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/vtc-aeroport-toulouse-blagnac': typeof VtcAeroportToulouseBlagnacRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mentions-legales'
    | '/politique-confidentialite'
    | '/vtc-aeroport-toulouse-blagnac'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mentions-legales'
    | '/politique-confidentialite'
    | '/vtc-aeroport-toulouse-blagnac'
  id:
    | '__root__'
    | '/'
    | '/mentions-legales'
    | '/politique-confidentialite'
    | '/vtc-aeroport-toulouse-blagnac'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PolitiqueConfidentialiteRoute: typeof PolitiqueConfidentialiteRoute
  VtcAeroportToulouseBlagnacRoute: typeof VtcAeroportToulouseBlagnacRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vtc-aeroport-toulouse-blagnac': {
      id: '/vtc-aeroport-toulouse-blagnac'
      path: '/vtc-aeroport-toulouse-blagnac'
      fullPath: '/vtc-aeroport-toulouse-blagnac'
      preLoaderRoute: typeof VtcAeroportToulouseBlagnacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-confidentialite': {
      id: '/politique-confidentialite'
      path: '/politique-confidentialite'
      fullPath: '/politique-confidentialite'
      preLoaderRoute: typeof PolitiqueConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PolitiqueConfidentialiteRoute: PolitiqueConfidentialiteRoute,
  VtcAeroportToulouseBlagnacRoute: VtcAeroportToulouseBlagnacRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
